# Generated by Django 5.2.5 on 2026-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('SECTION', 'Section')], default='LECTURE', max_length=10),
        ),
    ]
