# Generated by Django 5.2.5 on 2026-06-25 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section_group',
            field=models.IntegerField(blank=True, help_text='Section 1 to 5', null=True),
        ),
        migrations.CreateModel(
            name='SubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_group', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_taught', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_sections', to='lms_app.subject')),
            ],
            options={
                'unique_together': {('subject', 'section_group')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='subject_section',
            field=models.ForeignKey(blank=True, help_text='Linked to a specific section if MaterialType is SECTION.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lms_app.subjectsection'),
        ),
    ]
