# Generated by Django 5.2.5 on 2026-06-25 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_assignment_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_made', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='lms_app.subject')),
                ('subject_section', models.ForeignKey(blank=True, help_text='Linked to a specific section if created by a section instructor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_announcements', to='lms_app.subjectsection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
