# Generated by Django 5.2.5 on 2026-06-25 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='pin_duration_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
