# Generated by Django 5.2.5 on 2026-06-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_attendancesession_is_makeup_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
