# Generated by Django 5.2.5 on 2026-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_announcement_expires_at_announcement_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
