# Generated by Django 5.2.5 on 2026-06-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_rename_uploaded_at_material_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='official_book',
            field=models.FileField(blank=True, null=True, upload_to='official_books/'),
        ),
    ]
