# Generated by Django 5.2.5 on 2026-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowed_extensions',
            field=models.CharField(default='pdf,zip,docx,rar', max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_file_size_mb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='requirements_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
