# Generated by Django 5.2.5 on 2026-06-25 07:00

from django.db import migrations, models

import lms_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_assignment_allowed_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=lms_app.models.get_material_upload_path),
        ),
        migrations.AlterField(
            model_name='subject',
            name='official_book',
            field=models.FileField(blank=True, null=True, upload_to=lms_app.models.get_book_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(upload_to=lms_app.models.get_submission_upload_path),
        ),
    ]
