# Generated by Django 5.2.5 on 2026-06-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0016_alter_material_file_alter_subject_official_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
