# Generated by Django 5.2.5 on 2026-06-26 16:17

import django.db.models.deletion
from django.db import migrations, models

import lms_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms_app.material'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_files',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allowed_extensions',
            field=models.CharField(default='.pdf,.docx,.zip', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to=lms_app.models.get_submission_upload_path),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lms_app.models.get_submission_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lms_app.submission')),
            ],
        ),
    ]
