# Generated by Django 5.2.5 on 2026-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0018_assignment_lecture_assignment_max_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Manually open or close submissions'),
        ),
    ]
