# Generated by Django 5.2.5 on 2026-06-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0020_admindevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flagged for manual review (e.g. English name translation)'),
        ),
    ]
