# Generated by Django 5.2.5 on 2026-06-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0021_user_date_of_birth_user_gender_user_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_subjects',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='lms_app.subject'),
        ),
    ]
