# Generated by Django 5.2.5 on 2026-06-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0023_globalannouncement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='subject_section',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
    ]
