# Generated by Django 5.2.5 on 2026-06-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0025_subject_max_total_grade_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='كود المادة'),
        ),
    ]
