# Generated by Django 5.2.5 on 2026-06-28 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0026_alter_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('google_form_link', models.URLField(max_length=500, verbose_name='رابط امتحان Google Form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='lms_app.subject', verbose_name='المادة')),
            ],
        ),
    ]
