# Generated by Django 5.2.5 on 2026-06-28 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0027_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='google_form_link',
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='تعليمات الامتحان'),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='مدة الامتحان (بالدقائق)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت غلق الامتحان'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مفعل (يمكن إيقافه يدوياً)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_answers',
            field=models.BooleanField(default=False, verbose_name='إظهار الإجابات الصحيحة للطالب'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_score',
            field=models.BooleanField(default=True, verbose_name='إظهار الدرجة للطالب بعد التسليم'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت فتح الامتحان'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('score', models.FloatField(default=0.0, verbose_name='الدرجة')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='تم التسليم')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms_app.exam', verbose_name='الامتحان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('MCQ', 'اختيار من متعدد'), ('TF', 'صح وخطأ')], default='MCQ', max_length=3, verbose_name='نوع السؤال')),
                ('marks', models.PositiveIntegerField(default=1, verbose_name='درجة السؤال')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms_app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='نص الاختيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lms_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms_app.examattempt', verbose_name='المحاولة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.question', verbose_name='السؤال')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.choice', verbose_name='الاختيار المحدد')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
