# Generated by Django 5.2.5 on 2026-06-28 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0028_remove_exam_google_form_link_exam_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('LECTURE', 'محاضرة'), ('SECTION', 'سكشن')], default='LECTURE', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='lms_app.subjectsection'),
        ),
    ]
