# Generated by Django 5.2.5 on 2026-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0029_exam_creator_exam_exam_type_exam_subject_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsection',
            name='max_total_grade',
            field=models.IntegerField(default=50),
        ),
    ]
